import { expect, test } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import AxeBuilder from '@axe-core/playwright';

test('address creation recovery, address copy and filter, clipboard fallback, and return to list position', async ({ page, context }) => {
  const credentials = JSON.parse(await readFile('.local/local-access.json', 'utf8'));
  await page.goto('/');
  await page.getByLabel('아이디', { exact: true }).fill(credentials.username);
  await page.getByLabel('비밀번호', { exact: true }).fill(credentials.password);
  await page.getByRole('button', { name: '로그인', exact: true }).click();
  await expect(page.getByRole('combobox', { name: '메일함' })).toBeVisible();
  const local = `ux-${Date.now()}`;
  await page.getByRole('button', { name: '주소 만들기', exact: true }).first().click();
  await page.getByLabel('주소 이름').fill(local);
  await context.route('**/api/addresses', route => route.fulfill({ status: 503, json: { error: '연결을 확인해 주세요.' } }));
  await page.getByRole('button', { name: '만들고 복사' }).click();
  await expect(page.getByRole('alert')).toContainText('연결을 확인');
  await expect(page.getByLabel('주소 이름')).toHaveValue(local);
  await context.unroute('**/api/addresses');
  await page.getByRole('button', { name: '만들고 복사' }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(`${local}@bluekite.co.kr`);
  await page.getByRole('button', { name: '주소', exact: true }).click();
  await page.getByRole('searchbox', { name: '주소 검색' }).fill(local);
  await page.getByRole('button', { name: `${local}@bluekite.co.kr 복사`, exact: true }).click();
  await expect(page.getByRole('dialog').getByRole('status')).toContainText('복사됨');
  expect(await page.evaluate(() => navigator.clipboard.readText())).toBe(`${local}@bluekite.co.kr`);
  await page.getByRole('button', { name: `${local}@bluekite.co.kr 메일 보기`, exact: true }).click();
  await expect(page.getByRole('dialog')).toHaveCount(0);
  await expect(page.getByRole('heading', { name: '메일이 없습니다', exact: true })).toBeVisible();
  await expect(page.getByRole('button', { name: '주소 필터 해제' })).toBeVisible();
  await page.reload();
  await expect(page.getByRole('button', { name: '주소 필터 해제' })).toBeVisible();
  await page.getByRole('button', { name: '주소 필터 해제' }).click();
  await Promise.all(Array.from({ length: 12 }, async (_, index) => {
    const raw = [`From: UX Check <test@example.net>`, `To: ${local}@bluekite.co.kr`, `Message-ID: <${local}-${index}@example.net>`, `Subject: Verification code ${index}`, 'Content-Type: text/plain; charset=utf-8', '', 'Your verification code is 082916.'].join('\r\n');
    const response = await context.request.post(`/cdn-cgi/handler/email?from=test@example.net&to=${local}@bluekite.co.kr`, { data: raw, headers: { 'Content-Type': 'text/plain' } });
    expect(response.ok()).toBe(true);
  }));
  await page.getByRole('button', { name: '새로고침', exact: true }).click();
  await expect(page.locator('.row-code').first()).toBeVisible();
  const code = (await page.locator('.row-code').first().innerText()).trim();
  await page.evaluate(() => {
    const original = navigator.clipboard.writeText.bind(navigator.clipboard);
    navigator.clipboard.writeText = async () => { navigator.clipboard.writeText = original; throw new DOMException('Denied', 'NotAllowedError'); };
  });
  await page.locator('.row-code').first().click();
  const input = page.getByRole('textbox', { name: '인증번호', exact: true });
  await expect(input).toHaveValue(code);
  expect(await input.evaluate(node => [(node as HTMLInputElement).selectionStart, (node as HTMLInputElement).selectionEnd])).toEqual([0, code.length]);
  await page.keyboard.press('Escape');
  await expect(page.getByRole('dialog')).toHaveCount(0);
  const audit = await new AxeBuilder({ page }).withTags(['wcag2a', 'wcag2aa', 'wcag21aa']).analyze();
  expect(audit.violations.map(v => ({ id: v.id, nodes: v.nodes.map(n => n.target) }))).toEqual([]);

  await page.setViewportSize({ width: 375, height: 812 });
  const target = page.locator('.row-open').nth(9);
  await target.scrollIntoViewIfNeeded();
  const position = await page.evaluate(() => window.scrollY);
  expect(position).toBeGreaterThan(200);
  await target.click();
  await expect(page.getByRole('button', { name: '메일 목록으로' })).toBeFocused();
  expect(await page.evaluate(() => window.scrollY)).toBe(0);
  await page.goBack();
  await expect(target).toBeFocused();
  await expect.poll(() => page.evaluate(() => window.scrollY)).toBe(position);
  await target.click();
  await page.keyboard.press('ControlOrMeta+k');
  await expect(page.getByRole('searchbox', { name: '메일 검색' })).toBeFocused();
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
});
